version: '3.8'

services:
  jncep-service:
    image: ghcr.io/itslightmind/jncep-web-service:latest
    container_name: jncep-container
    ports:
      - "5000:5000"
    volumes:
      - CHANGE_ME/downloads:/app/downloads
      - CHANGE_ME/config:/root/.config/jncep
    environment:
      - JNCEP_EMAIL=EMAIL_HERE
      - JNCEP_PASSWORD=PASSWORD_HERE
      # Optionally, uncomment the next line if you have a Discord webhook URL, dont wrap quotes around it.
      # - DISCORD_WEBHOOK_URL=

  cron-service: # this automates the syncing of tracked series
    image: willfarrell/crontab
    depends_on:
      - jncep-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_LABELS=TRUE
    labels:
      - cron.sync_job.schedule=0,20,40 * * * * # by default this runs every 20 minutes on the hour, to change this you just have to search a cron calculator
      - cron.sync_job.command=curl -s http://jncep-service:5000/sync
