version: '3.8'

services:
  jncep-service:
    build: .
    container_name: jncep-container
    ports:
      - "5000:5000"
    volumes:
      - /path/to/downloads:/app/downloads
      - /path/to/store/config:/root/.config/jncep
    environment:
      - JNCEP_EMAIL=EMAIL_HERE
      - JNCEP_PASSWORD=PASSWORD_HERE
      # Optionally, uncomment the next line if you have a Discord webhook URL, dont wrap quotes around it.
      # - DISCORD_WEBHOOK_URL=
