version: '3.8'

services:
  jncep-service:
    image: ghcr.io/itslightmind/jncep-web-service:latest
    container_name: jncep-container
    ports:
      - "5000:5000"
    volumes:
      - CHANGE_ME/downloads:/app/downloads
      - CHANGE_ME/config:/root/.config/jncep
    environment:
      - JNCEP_EMAIL=EMAIL_HERE
      - JNCEP_PASSWORD=PASSWORD_HERE
      # Optionally, uncomment the next line if you have a Discord webhook URL, dont wrap quotes around it.
      # - DISCORD_WEBHOOK_URL=

  cron:
    image: alpine:latest
    environment:
      - CRON_FREQUENCY=*/20 * * * * # Every 20 minutes
      # You can change the above line to "0 * * * *" for every hour
      # or "*/30 * * * *" for every 30 minutes, etc.
    entrypoint: /bin/sh -c
    command: |
      apk add --no-cache curl &&
      (echo "$CRON_FREQUENCY /usr/bin/curl -s http://jncep-service:5000/sync" > /etc/crontabs/root) &&
      crond -l 2 -f &&
      tail -f /dev/null