version: '3.8'

services:
  jncep-service:
    image: ghcr.io/itslightmind/jncep-web-service:latest
    container_name: jncep-container
    ports:
      - "5000:5000"
    volumes:
      - CHANGE_ME/downloads:/app/downloads
      - CHANGE_ME/config:/root/.config/jncep
    environment:
      - JNCEP_EMAIL=EMAIL_HERE
      - JNCEP_PASSWORD=PASSWORD_HERE
      # Optionally, uncomment the next line if you have a Discord webhook URL, dont wrap quotes around it.
      # - DISCORD_WEBHOOK_URL=

  # Set up the cron job with the desired frequency
  # Use "*/20 * * * *" for every 20 minutes
  # Use "0 * * * *" for hourly
  # Use "0 */2 * * *" for every 2 hours
  # Use "0 */30 * * *" for every 30 minutes
  cron:
    image: alpine:latest
    entrypoint: /bin/sh -c
    command: |
      "apk add --no-cache curl &&
      (echo '*/20 * * * * /usr/bin/curl -s http://jncep-service:5000/sync' > /etc/crontabs/root) &&
      crond -l 2 -f &&
      tail -f /dev/null"